### ISSUE TITLE
Potential build structure for site 2.0

### ISSUE THREAD

**Issue by elainekamlley** [18F/beta.18f.gov#1]
For the new site, spoke with @msecret and @gboone about possible ways to build the site. There are few ways: 
- npm build
- jekyll build 

One issue we'll run into (and we see it now with the current site) with all of the assets, the build takes a long time. Trying to figure out ways to reduce this.

**Comment by gboone** [comment]
One thing I realized I didn't understand when we chatted earlier: Would the NPM build only build the CSS and JS or is this about migrating from Jekyll?

**Comment by msecret** [comment]
I think if we use Jekyll, we have to use a ruby build with jekyll plugins. This is because jekyll kind of forces you to stick with it's way of doing things.

If we migrated to Hugo for instance (not saying we should, just to provide context), then it's more agnostic about build and we'd like have an npm build process for CSS, JS, images.

**Comment by gboone** [comment]
Curious what @msecret and @elainekamlley think about using a Federalist template, namely the [federalist modern template](https://github.com/18f/federalist-modern-team-template). Knowing that we'll be customizing it pretty heavily, especially for the Dashboard, there's a few questions to consider:
- Is it worth starting with a template to solve for a lot of common problems rather than start completely from scratch.
- Is there a good way to make sure we keep up to date with upstream changes? Does it matter if we don't get them?

**Comment by msecret** [comment]
Hi @gboone .

I think that's a great idea. That template uses web design standards, which we were planning to build from. Federalist also makes it easy to modify the CSS to your needs.

I've heard the template won't change that much, so not sure that will be a concern. I actually think the web standards will be the thing that changes a lot, but we can be smart about what changes we bring in.

**Comment by gboone** [comment]
> we can be smart about what changes we bring in.

I'm intrigued, how would we do that and why not bring in all the updates when they're stable?

**Comment by msecret** [comment]
What I mean by that is that we'd wait until things are stable before we bring them in. Standards will put out versioned releases which we can pull in when we need certain components.

**Comment by gboone** [comment]
Nice. I like it. @elainekamlley, thoughts?

**Comment by hbillings** [comment]
It seems like we're using Federalist for this. Can we close this issue?
